### ISSUE TITLE
 How to compile using minGW64

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [microwavesafe/lv_sim_vscode_sdl#60]
![image](https://github.com/user-attachments/assets/a9142230-c863-471b-8802-682be23f00e9)

**Comment by kisvegabor** [comment]
It should be fixed in the latest `master` by this https://github.com/lvgl/lv_port_pc_vscode/commit/e08bfca8aab3fe548075ae2176751fa6186de812

Do you use the latest `master`?

**Comment by aixiaoxiaoyu** [comment]
> It should be fixed in the latest `master` by this [e08bfca](https://github.com/lvgl/lv_port_pc_vscode/commit/e08bfca8aab3fe548075ae2176751fa6186de812)
> 
> Do you use the latest `master`?
Yes
![image](https://github.com/user-attachments/assets/8c6718d2-a7e8-4326-9e4d-dbd13df0511f)

**Comment by kisvegabor** [comment]
It seems CMake fails to detect ASAN with MinGW.

With the PR ASAN needs to be enabled explicitly. Does it work with these changes?
